language: php
php:
    - '7.2'
    - '7.3'
    - '7.4'
install:
    # prefer source for required phpunit.xml
    - composer install --prefer-source
    - touch vendor/phile-cms/phile/lib/vendor/autoload.php
    - mkdir -p vendor/phile-cms/phile/plugins/siezi/phileDebugbar
    - find . -maxdepth 1 ! -path ./vendor ! -path . -exec mv \{\} vendor/phile-cms/phile/plugins/siezi/phileDebugbar \;
script:
    - vendor/bin/phpunit -c vendor/phile-cms/phile/phpunit.xml  vendor/phile-cms/phile/plugins/siezi/phileDebugbar/